[tasks.run-native]
env_files = ["../../.env"]
script_runner = "@shell"
script.pre = "rm -fr ./assets/* && cp -r ../../assets ."
script.main = "mold -run cargo run --features inspect"
watch.watch = [
    "../../src",
    "../../assets",
    "../../Cargo.toml",
    "src",
    "Cargo.toml",
]

[tasks.release-native]
env_files = ["../../.env"]
command = "mold"
args = ["-run", "cargo", "build", "--release"]
